DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 1, 'IT' );
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 2, 'SECURITY' );
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 3, 'MANAGEMENT' );