DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	SALARY INT NOT NULL,
	DEPARTMENT_ID INT NOT NULL,
	CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
	CONSTRAINT EMPLOYEE_DEPARTMENT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);


INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 1, 'IT' );
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 2, 'SECURITY' );
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 3, 'MANAGEMENT' );

INSERT INTO EMPLOYEE (employee_id, firstname, lastname, email, salary, department_id) VALUES (1, 'FirstName1', 'LastName1', 'employee1@mail.com', 100, 1);
INSERT INTO EMPLOYEE (employee_id, firstname, lastname, email, salary, department_id) VALUES (2, 'FirstName2', 'LastName2', 'employee2@mail.com', 200, 1);
INSERT INTO EMPLOYEE (employee_id, firstname, lastname, email, salary, department_id) VALUES (3, 'FirstName3', 'LastName3', 'employee3@mail.com', 300, 2);
